name: T_able
description: A smart productivity Flutter app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analog_clock: ^0.0.4
  bubble: ^1.1.9+1
  cupertino_icons: ^0.1.3
  curved_navigation_bar: ^0.3.4
  flutter_datetime_picker: ^1.4.0
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.0+2
  image_pickers: ^1.0.8+7
  path_provider: ^1.6.24
  flutter_bloc: ^6.1.2
  unicorndial: ^1.1.5
  url_launcher: ^5.7.6
  flutter_secure_storage: ^3.3.5
  progress_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
